const allDonationData = {
  checkdams: [
    {
      id: "donation-for-biggest-checkdam",
      type: "checkdam",
      amount: "₹1,00,00,000",
      rawAmount: 10000000,
      title: "Donation for Biggest Checkdam",
      img: "/image/suport/Donation-Biggest-Size.png",
      desc: "Support the construction of a largest-scale check dam that can store significant rainwater, recharge groundwater, and provide long-term water security for entire villages.",
      related: [
        {
          id: "donation-for-large-checkdam",
          title: "Large Checkdam Project",
          amount: "₹50,00,000",
          img: "/image/suport/Donation-Large-Size.png",
          desc: "Contribute towards building a large check dam that helps collect rainwater, improve irrigation for farmers, and increase groundwater levels in drought-prone areas.",
        },
        {
          id: "donation-for-medium-checkdam",
          title: "Medium Checkdam Project",
          amount: "₹20,00,000",
          img: "/image/suport/Donation-Medium-Size.png",
          desc: "Help construct a medium-sized check dam that supports local farming communities by storing seasonal water and improving groundwater recharge.",
        },
        {
          id: "donation-for-small-checkdam",
          title: "Small Checkdam Project",
          amount: "₹5,00,000",
          img: "/image/suport/Donation-Small-Size.png",
          desc: "Donate to build a small check dam that captures rainwater, prevents soil erosion, and supports nearby farmers and wildlife with essential water resources.",
        },
      ],
    },
    {
      id: "donation-for-large-checkdam",
      type: "checkdam",
      amount: "₹50,00,000",
      rawAmount: 5000000,
      title: "Donation for Large Checkdam",
      img: "/image/suport/Donation-Large-Size.png",
      desc: "Contribute towards building a large check dam that helps collect rainwater, improve irrigation for farmers, and increase groundwater levels in drought-prone areas.",
      related: [
        {
          id: "donation-for-biggest-checkdam",
          title: "Biggest Checkdam Project",
          amount: "₹1,00,00,000",
          img: "/image/suport/Donation-Biggest-Size.png",
          desc: "Support the construction of a largest-scale check dam that can store significant rainwater, recharge groundwater, and provide long-term water security for entire villages.",
        },
        {
          id: "donation-for-medium-checkdam",
          title: "Medium Checkdam Project",
          amount: "₹20,00,000",
          img: "/image/suport/Donation-Medium-Size.png",
          desc: "Help construct a medium-sized check dam that supports local farming communities by storing seasonal water and improving groundwater recharge.",
        },
        {
          id: "donation-for-small-checkdam",
          title: "Small Checkdam Project",
          amount: "₹5,00,000",
          img: "/image/suport/Donation-Small-Size.png",
          desc: "Donate to build a small check dam that captures rainwater, prevents soil erosion, and supports nearby farmers and wildlife with essential water resources.",
        },
      ],
    },
    {
      id: "donation-for-medium-checkdam",
      type: "checkdam",
      amount: "₹20,00,000",
      rawAmount: 2000000,
      title: "Donation for Medium Checkdam",
      img: "/image/suport/Donation-Medium-Size.png",
      desc: "Help construct a medium-sized check dam that supports local farming communities by storing seasonal water and improving groundwater recharge.",
      related: [
        {
          id: "donation-for-biggest-checkdam",
          title: "Biggest Checkdam Project",
          amount: "₹1,00,00,000",
          img: "/image/suport/Donation-Biggest-Size.png",
          desc: "Support the construction of a largest-scale check dam that can store significant rainwater, recharge groundwater, and provide long-term water security for entire villages.",
        },
        {
          id: "donation-for-large-checkdam",
          title: "Large Checkdam Project",
          amount: "₹50,00,000",
          img: "/image/suport/Donation-Large-Size.png",
          desc: "Contribute towards building a large check dam that helps collect rainwater, improve irrigation for farmers, and increase groundwater levels in drought-prone areas.",
        },
        {
          id: "donation-for-small-checkdam",
          title: "Small Checkdam Project",
          amount: "₹5,00,000",
          img: "/image/suport/Donation-Small-Size.png",
          desc: "Donate to build a small check dam that captures rainwater, prevents soil erosion, and supports nearby farmers and wildlife with essential water resources.",
        },
      ],
    },
    {
      id: "donation-for-small-checkdam",
      type: "checkdam",
      amount: "₹5,00,000",
      rawAmount: 500000,
      title: "Donation for Small Checkdam",
      img: "/image/suport/Donation-Small-Size.png",
      desc: "Donate to build a small check dam that captures rainwater, prevents soil erosion, and supports nearby farmers and wildlife with essential water resources.",
      related: [
        {
          id: "donation-for-biggest-checkdam",
          title: "Biggest Checkdam Project",
          amount: "₹1,00,00,000",
          img: "/image/suport/Donation-Biggest-Size.png",
          desc: "Support the construction of a largest-scale check dam that can store significant rainwater, recharge groundwater, and provide long-term water security for entire villages.",
        },
        {
          id: "donation-for-large-checkdam",
          title: "Large Checkdam Project",
          amount: "₹50,00,000",
          img: "/image/suport/Donation-Large-Size.png",
          desc: "Contribute towards building a large check dam that helps collect rainwater, improve irrigation for farmers, and increase groundwater levels in drought-prone areas.",
        },
        {
          id: "donation-for-medium-checkdam",
          title: "Medium Checkdam Project",
          amount: "₹20,00,000",
          img: "/image/suport/Donation-Medium-Size.png",
          desc: "Help construct a medium-sized check dam that supports local farming communities by storing seasonal water and improving groundwater recharge.",
        },
      ],
    },
  ],

  maintainCheckdams: [
    {
      id: "donation-for-maintain-biggest-checkdam",
      type: "maintain-checkdam",
      amount: "₹1,00,00,000",
      rawAmount: 10000000,
      title: "Donation to Maintain Biggest Checkdam",
      img: "/image/suport/Donation-Biggest-Size-Checkdam.png",
      desc: "Your donation helps maintain, renovate, and deepen the biggest checkdam to store more water and support nearby villages.",
      related: [
        {
          id: "donation-for-maintain-large-checkdam",
          title: "Maintain Large Checkdam",
          amount: "₹50,00,000",
          img: "/image/suport/Donation-Large-Size-Checkdam.png",
          desc: "This contribution supports the maintenance, renovation, and deepening of a large checkdam to improve water conservation.",
        },
        {
          id: "donation-for-maintain-medium-checkdam",
          title: "Maintain Medium Checkdam",
          amount: "₹20,00,000",
          img: "/image/suport/Donation-Medium-Size-Checkdam.png",
          desc: "Your support helps repair, maintain, and deepen a medium-sized checkdam for better groundwater recharge.",
        },
        {
          id: "donation-for-maintain-small-checkdam",
          title: "Maintain Small Checkdam",
          amount: "₹5,00,000",
          img: "/image/suport/Donation-Small-Size-Checkdam.png",
          desc: "This donation helps maintain and restore a small checkdam to ensure water availability for farming and local use.",
        },
      ],
    },
    {
      id: "donation-for-maintain-large-checkdam",
      type: "maintain-checkdam",
      amount: "₹50,00,000",
      rawAmount: 5000000,
      title: "Donation to Maintain Large Checkdam",
      img: "/image/suport/Donation-Large-Size-Checkdam.png",
      desc: "This contribution supports the maintenance, renovation, and deepening of a large checkdam to improve water conservation.",
      related: [
        {
          id: "donation-for-maintain-biggest-checkdam",
          title: "Maintain Biggest Checkdam",
          amount: "₹1,00,00,000",
          img: "/image/suport/Donation-Biggest-Size-Checkdam.png",
          desc: "Your donation helps maintain, renovate, and deepen the biggest checkdam to store more water and support nearby villages.",
        },
        {
          id: "donation-for-maintain-medium-checkdam",
          title: "Maintain Medium Checkdam",
          amount: "₹20,00,000",
          img: "/image/suport/Donation-Medium-Size-Checkdam.png",
          desc: "Your support helps repair, maintain, and deepen a medium-sized checkdam for better groundwater recharge.",
        },
        {
          id: "donation-for-maintain-small-checkdam",
          title: "Maintain Small Checkdam",
          amount: "₹5,00,000",
          img: "/image/suport/Donation-Small-Size-Checkdam.png",
          desc: "This donation helps maintain and restore a small checkdam to ensure water availability for farming and local use.",
        },
      ],
    },
    {
      id: "donation-for-maintain-medium-checkdam",
      type: "maintain-checkdam",
      amount: "₹20,00,000",
      rawAmount: 2000000,
      title: "Donation to Maintain Medium Checkdam",
      img: "/image/suport/Donation-Medium-Size-Checkdam.png",
      desc: "Your support helps repair, maintain, and deepen a medium-sized checkdam for better groundwater recharge.",
      related: [
        {
          id: "donation-for-maintain-biggest-checkdam",
          title: "Maintain Biggest Checkdam",
          amount: "₹1,00,00,000",
          img: "/image/suport/Donation-Biggest-Size-Checkdam.png",
          desc: "Your donation helps maintain, renovate, and deepen the biggest checkdam to store more water and support nearby villages.",
        },
        {
          id: "donation-for-maintain-large-checkdam",
          title: "Maintain Large Checkdam",
          amount: "₹50,00,000",
          img: "/image/suport/Donation-Large-Size-Checkdam.png",
          desc: "This contribution supports the maintenance, renovation, and deepening of a large checkdam to improve water conservation.",
        },
        {
          id: "donation-for-maintain-small-checkdam",
          title: "Maintain Small Checkdam",
          amount: "₹5,00,000",
          img: "/image/suport/Donation-Small-Size-Checkdam.png",
          desc: "This donation helps maintain and restore a small checkdam to ensure water availability for farming and local use.",
        },
      ],
    },
    {
      id: "donation-for-maintain-small-checkdam",
      type: "maintain-checkdam",
      amount: "₹5,00,000",
      rawAmount: 500000,
      title: "Donation to Maintain Small Checkdam",
      img: "/image/suport/Donation-Small-Size-Checkdam.png",
      desc: "This donation helps maintain and restore a small checkdam to ensure water availability for farming and local use.",
      related: [
        {
          id: "donation-for-maintain-biggest-checkdam",
          title: "Maintain Biggest Checkdam",
          amount: "₹1,00,00,000",
          img: "/image/suport/Donation-Biggest-Size-Checkdam.png",
          desc: "Your donation helps maintain, renovate, and deepen the biggest checkdam to store more water and support nearby villages.",
        },
        {
          id: "donation-for-maintain-large-checkdam",
          title: "Maintain Large Checkdam",
          amount: "₹50,00,000",
          img: "/image/suport/Donation-Large-Size-Checkdam.png",
          desc: "This contribution supports the maintenance, renovation, and deepening of a large checkdam to improve water conservation.",
        },
        {
          id: "donation-for-maintain-medium-checkdam",
          title: "Maintain Medium Checkdam",
          amount: "₹20,00,000",
          img: "/image/suport/Donation-Medium-Size-Checkdam.png",
          desc: "Your support helps repair, maintain, and deepen a medium-sized checkdam for better groundwater recharge.",
        },
      ],
    },
  ],

  equipment: [
    {
      id: "donation-for-Water-Tanker",
      type: "equipment",
      amount: "₹2,50,000",
      rawAmount: 250000,
      title: "Donation for Water Tanker",
      img: "/image/suport/Water-Tanker.jpg",
      desc: "Your generous contribution will help us purchase and maintain a water tanker used to transport clean drinking water to villages and drought-affected areas. The tanker plays an important role during summer and water shortage periods, ensuring that families, farmers, and livestock have access to safe water. With your support, we can deliver water to remote communities and improve daily life for people who struggle to access this basic necessity.",
      related: [
        {
          id: "donation-for-tractor",
          title: "Donation for Tractor",
          amount: "₹7,50,000",
          img: "/image/suport/Tractor.jpg",
          desc: "Donating for a tractor helps support agricultural and rural development activities.",
        },
        {
          id: "donation-for-ace-pickup-tempo",
          title: "Donation for Ace Pickup Tempo",
          amount: "₹7,50,000",
          img: "/image/suport/Ace-Small-Truck.jpg",
          desc: "The Ace Pickup Tempo is a small utility vehicle that helps transport tools, construction materials.",
        },
        {
          id: "donation-for-loader",
          title: "Donation for Loader",
          amount: "₹15,00,000",
          img: "/image/suport/Loader.jpg",
          desc: "A loader machine is essential for construction, digging, and earth-moving work.",
        },
        {
          id: "donation-for-jcb",
          title: "Donation for JCB",
          amount: "₹40,00,000",
          img: "/image/suport/JCB.jpg",
          desc: "The JCB machine is one of the most important machines used in large-scale construction.",
        },
      ],
    },
    {
      id: "donation-for-tractor",
      type: "equipment",
      amount: "₹7,50,000",
      rawAmount: 750000,
      title: "Donation for Tractor",
      img: "/image/suport/Tractor.jpg",
      desc: "Donating for a tractor helps support agricultural and rural development activities. The tractor is used for farming operations, land preparation, transportation of materials, and maintenance of community projects such as checkdams and water conservation structures. Your donation helps farmers work more efficiently and supports sustainable development in rural areas.",
      related: [
        {
          id: "donation-for-Water-Tanker",
          title: "Donation for Water Tanker",
          amount: "₹2,50,000",
          img: "/image/suport/Water-Tanker.jpg",
          desc: "Your generous contribution will help us purchase and maintain a water tanker.",
        },
        {
          id: "donation-for-ace-pickup-tempo",
          title: "Donation for Ace Pickup Tempo",
          amount: "₹7,50,000",
          img: "/image/suport/Ace-Small-Truck.jpg",
          desc: "The Ace Pickup Tempo is a small utility vehicle that helps transport tools, construction materials.",
        },
        {
          id: "donation-for-loader",
          title: "Donation for Loader",
          amount: "₹15,00,000",
          img: "/image/suport/Loader.jpg",
          desc: "A loader machine is essential for construction, digging, and earth-moving work.",
        },
        {
          id: "donation-for-jcb",
          title: "Donation for JCB",
          amount: "₹40,00,000",
          img: "/image/suport/JCB.jpg",
          desc: "The JCB machine is one of the most important machines used in large-scale construction.",
        },
      ],
    },
    {
      id: "donation-for-ace-pickup-tempo",
      type: "equipment",
      amount: "₹7,50,000",
      rawAmount: 750000,
      title: "Donation for Ace Pickup Tempo",
      img: "/image/suport/Ace-Small-Truck.jpg",
      desc: "The Ace Pickup Tempo is a small utility vehicle that helps transport tools, construction materials, and essential supplies to villages and project sites. It is especially useful for reaching narrow rural roads where larger vehicles cannot go. Your support will help us deliver resources quickly and efficiently for development and water conservation initiatives.",
      related: [
        {
          id: "donation-for-Water-Tanker",
          title: "Donation for Water Tanker",
          amount: "₹2,50,000",
          img: "/image/suport/Water-Tanker.jpg",
          desc: "Your generous contribution will help us purchase and maintain a water tanker.",
        },
        {
          id: "donation-for-tractor",
          title: "Donation for Tractor",
          amount: "₹7,50,000",
          img: "/image/suport/Tractor.jpg",
          desc: "Donating for a tractor helps support agricultural and rural development activities.",
        },
        {
          id: "donation-for-loader",
          title: "Donation for Loader",
          amount: "₹15,00,000",
          img: "/image/suport/Loader.jpg",
          desc: "A loader machine is essential for construction, digging, and earth-moving work.",
        },
        {
          id: "donation-for-jcb",
          title: "Donation for JCB",
          amount: "₹40,00,000",
          img: "/image/suport/JCB.jpg",
          desc: "The JCB machine is one of the most important machines used in large-scale construction.",
        },
      ],
    },
    {
      id: "donation-for-loader",
      type: "equipment",
      amount: "₹15,00,000",
      rawAmount: 1500000,
      title: "Donation for Loader",
      img: "/image/suport/Loader.jpg",
      desc: "A loader machine is essential for construction, digging, and earth-moving work required in building and maintaining water conservation structures like checkdams and ponds. With your donation, we can speed up project work, reduce manual labor, and complete infrastructure projects that benefit farmers and nearby communities.",
      related: [
        {
          id: "donation-for-Water-Tanker",
          title: "Donation for Water Tanker",
          amount: "₹2,50,000",
          img: "/image/suport/Water-Tanker.jpg",
          desc: "Your generous contribution will help us purchase and maintain a water tanker.",
        },
        {
          id: "donation-for-tractor",
          title: "Donation for Tractor",
          amount: "₹7,50,000",
          img: "/image/suport/Tractor.jpg",
          desc: "Donating for a tractor helps support agricultural and rural development activities.",
        },
        {
          id: "donation-for-ace-pickup-tempo",
          title: "Donation for Ace Pickup Tempo",
          amount: "₹7,50,000",
          img: "/image/suport/Ace-Small-Truck.jpg",
          desc: "The Ace Pickup Tempo is a small utility vehicle that helps transport tools, construction materials.",
        },
        {
          id: "donation-for-jcb",
          title: "Donation for JCB",
          amount: "₹40,00,000",
          img: "/image/suport/JCB.jpg",
          desc: "The JCB machine is one of the most important machines used in large-scale construction.",
        },
      ],
    },
    {
      id: "donation-for-jcb",
      type: "equipment",
      amount: "₹40,00,000",
      rawAmount: 4000000,
      title: "Donation for JCB",
      img: "/image/suport/JCB.jpg",
      desc: "The JCB machine is one of the most important machines used in large-scale construction and water conservation work. It helps in digging ponds, deepening checkdams, cleaning canals, and preparing land for community projects. Your generous donation will help us carry out major development work that improves water storage, supports agriculture, and benefits entire villages.",
      related: [
        {
          id: "donation-for-Water-Tanker",
          title: "Donation for Water Tanker",
          amount: "₹2,50,000",
          img: "/image/suport/Water-Tanker.jpg",
          desc: "Your generous contribution will help us purchase and maintain a water tanker.",
        },
        {
          id: "donation-for-tractor",
          title: "Donation for Tractor",
          amount: "₹7,50,000",
          img: "/image/suport/Tractor.jpg",
          desc: "Donating for a tractor helps support agricultural and rural development activities.",
        },
        {
          id: "donation-for-ace-pickup-tempo",
          title: "Donation for Ace Pickup Tempo",
          amount: "₹7,50,000",
          img: "/image/suport/Ace-Small-Truck.jpg",
          desc: "The Ace Pickup Tempo is a small utility vehicle that helps transport tools, construction materials.",
        },
        {
          id: "donation-for-loader",
          title: "Donation for Loader",
          amount: "₹15,00,000",
          img: "/image/suport/Loader.jpg",
          desc: "A loader machine is essential for construction, digging, and earth-moving work.",
        },
      ],
    },
  ],
};

// ─── Helper: find any item by ID across all categories ───────────────────────
export function getDonationById(id: string) {
  const all = [
    ...allDonationData.checkdams,
    ...allDonationData.maintainCheckdams,
    ...allDonationData.equipment,
  ];
  return all.find((item) => item.id === id) ?? null;
}

// ─── Named flat exports for section pages ────────────────────────────────────
export const donateData = allDonationData.checkdams;
export const maintaindonateData = allDonationData.maintainCheckdams;
export const donationequipment = allDonationData.equipment;

export default allDonationData;